# SPDX-License-Identifier: GPL-2.0

ccflags-y += -I$(srctree)/$(src)
ccflags-y += -I$(srctree)/drivers/interconnect
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/iommu
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/mtk-interconnect
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/qos
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/vcp/include
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/vcp/rv
ccflags-y += -I$(DEVICE_MODULES_PATH)/drivers/misc/mediatek/include
obj-$(CONFIG_INTERCONNECT_MTK_EMI) += mtk-emi.o
